const ROOM_ID = 21452505
const LIVE_SESSION_PREFIX = `live:${ROOM_ID}:session`

export const Consts = {
  SCALE_REGEX: /^(\d+)([dm])$/,
  LIVE_INFO_TTL: 60,
  ROOM_ID: ROOM_ID,
  LIVE_SESSION_PREFIX: LIVE_SESSION_PREFIX,
  LIVE_SESSION_LATEST_KEY: `${LIVE_SESSION_PREFIX}:latest`,
  LIVE_INFO_CACHE_KEY: `live:${ROOM_ID}:info`,
  LIVE_SESSIONS_METRICS_PREFIX: `live:${ROOM_ID}:metrics:sessions`,
  LIVE_SESSIONS_METRICS_CACHE_TTL: 6 * 60 * 60, // 6h
}
